<div class="hero-unit">
    <h1 class="zf-green">Authentication</h1>
    <p>Please log in</p>
</div>
<div class="row">
    <div class="span4">&nbsp;</div>
    <div class="span4 box">
        <?php
        if (isset($this->session->user)) {
            echo "<h3 class='zf-green'>You are already logged in as (".$this->session->uid.")</h3>";
            echo "<p><a href='/user/logout'>If you would like to sign out please click here</a></p>";
        } else {
            if (isset($this->error)) {
                echo "<h3 class='error'>" . $this->error . "</h3>";
            }
            if (isset($this->form)) {
                $form = $this->form;
                $form->setAttribute('action',$this->url('ldap-login-route',array('action'=>'login')));
                $form->prepare();

                echo $this->form()->openTag($form);
                echo $this->formCollection($form);
                echo $this->form()->closeTag();
            } else {
                if (isset($this->data)) {
                    echo $this->data;
                }
            }
        }
        ?>
    </div>
    <div class="span4">&nbsp;</div>
</div>