<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Zf2LdapAuth\Module'                            => __DIR__ . '/Module.php',
    'Zf2LdapAuth\Controller\LoginController'        => __DIR__ . '/src/Zf2LdapAuth/Controller/LoginController.php',
    'Zf2LdapAuth\Controller\LogoutController'       => __DIR__ . '/src/Zf2LdapAuth/Controller/LogoutController.php',
    'Zf2LdapAuth\Forms\Login'                       => __DIR__ . '/src/Zf2LdapAuth/Forms/Login.php',
    'Zf2LdapAuth\Model\LdapInterface'               => __DIR__ . '/src/Zf2LdapAuth/Model/LdapInterface.php',
    'Zf2LdapAuth\ServiceFactory\LdapServiceFactory' => __DIR__ . '/src/Zf2LdapAuth/ServiceFactory/LdapServiceFactory.php',
);